### ISSUE TITLE
Home Page Template

### ISSUE THREAD

**Issue by d4mation** [automatedlogistics/Theme2016#1]

**Comment by d4mation** [comment]
Font Awesome Icons in 5050560 are placeholders for now.

**Comment by BigActual** [comment]
@d4mation- Do you need these icons?

**Comment by d4mation** [comment]
I have the icons as Rasters (`.JPEG` or `.PNG`, I cannot remember which).

It would be preferable to have them as `.SVG` or `.EPS`, because then I can convert them into an Icon Font like FontAwesome or IcoMoon. Otherwise I'll probably include the files in the Theme Directory and serve them up statically that way. I'd rather not make an Image Upload box for them as that may lead to some strangely sized stuff in there.

**Comment by BigActual** [comment]
@skarritt, when you return from vacation, would you provide SVGs please?

**Comment by BigActual** [comment]
bump @skarritt
