### ISSUE TITLE
404 Template

### ISSUE THREAD

**Issue by d4mation** [automatedlogistics/Theme2016#10]
Within brand. 

> Also, what information would be helpful on an ALS 404 page? What choices should be available?  (visual of a trucker looking at a map - as if lost.  Verbiage talks about how ALS can “get them back on track”)
- Link to home
- Link to various Services
- Link to Carrier Page
- Link to Shippers Page
- Link to Employment Page

**Comment by d4mation** [comment]
As the 404 template doesn't normally give the User any way to control what is visible, I added a couple Customizer Controls that only apply to the 404 Template.

![image](https://cloud.githubusercontent.com/assets/7770631/14215083/c9ddd094-f80e-11e5-9644-047cb35bf491.png)

There is also a Sidebar/Widget Area specific to the 404 Template that can be used to put in a Menu or whatever other Widgets that are wanted to help navigate the User back to what they're looking for.

![image](https://cloud.githubusercontent.com/assets/7770631/14215119/f9875ebe-f80e-11e5-89ee-4d964145d31d.png)

**Comment by BigActual** [comment]
Fancy. So the copy under the error message is editable then? Great. @skarritt... Thoughts?
