### ISSUE TITLE
Client Request for Akismet API Key

### ISSUE THREAD

**Issue by BigActual** [automatedlogistics/Theme2016#100]
Owie, I would like to turn on Akismet, a piece of software that limits comment spam. It's become a standard tool for most WordPress sites because it's very effective at keeping spammers from comment spamming a website. There is nothing like that built into core, it's definitely an add-on. 

It requires an API key and there is a monthly charge, **technically**, for commercial accounts. You'll see what I mean during the signup process. Because of the potential charge and the need to tether the account to an ALS email, I'd like an ALS employee to obtain the key and maintain the Akismet payments if chosen. 

The key is created by going here and signing up: https://akismet.com/

I can walk you through the signup process if you'd like, just give me a call, or paste the key in here if there are no questions about this at your end.

**Comment by brashrebel** [comment]
This isn't a private repository so I'd recommend sharing the key privately. But thanks @BigActual for making this happen.
