### ISSUE TITLE
Image for product tile

### ISSUE THREAD

**Issue by lsextonALS** [automatedlogistics/Theme2016#106]
This image needs to replace the current image for the Specialized tile on the customers page.  When I tried to upload the svg file to wordpress, it said that file type is not permitted for security reasons. @brashrebel @d4mation 
[DD90x90.zip](https://github.com/automatedlogistics/Theme2016/files/937417/DD90x90.zip)

**Comment by d4mation** [comment]
@lsextonALS I've tried to open your SVG in InkScape and it doesn't show for me at all, but looking at the document properties I can tell it isn't configured correctly.

From the Edit Screen for Products/Services:

> If using an SVG, ensure to set the Height and Width of the Document to 90px x 90px. Also, ensure the Vector is a Single Path. This means no overlaying Shapes or using Strokes. From there, center within the 90px x 90px square as appropriate for the proportions of the Vector.

When I open the file in InkScape (Or open the SVG in a text editor) I can see that the Height and Width of the SVG itself are not set to be a perfect square:

![image](https://cloud.githubusercontent.com/assets/7770631/25198304/0bedfb92-2515-11e7-8f4a-28d1da44f3ce.png)

The Document itself should be set to 90 pixels by 90 pixels. This is to help ensure that each item in the Grid is an equal height and width allowing it to look nice.

I'll look into that error on Upload though. It was definitely working back before launch.

**Comment by lsextonALS** [comment]
The artboard was set to 90pxx90px, however I'm no svg expert, so maybe I exported it incorrectly?
![capture](https://cloud.githubusercontent.com/assets/22197968/25198697/5dbcbd4a-2516-11e7-9fc0-601f3ae5bb24.PNG)

**Comment by d4mation** [comment]
You need to set those options when you create the Document, like so:

![image](https://cloud.githubusercontent.com/assets/7770631/25200302/d982ed8c-251b-11e7-9fdd-bceebbffb54b.png)

Here's the corrected file. I believe I've fixed the SVG upload issue.

[DD90x90-edit.svg.zip](https://github.com/automatedlogistics/Theme2016/files/938149/DD90x90-edit.svg.zip)

**Comment by d4mation** [comment]
Also, `File -> Save As` and choosing SVG from the Format dropdown worked fine for me. After I did that with your file, I was able to open it in InkScape.
