### ISSUE TITLE
Create Survey Forms for Customer Satisfaction

### ISSUE THREAD

**Issue by BigActual** [automatedlogistics/Theme2016#108]
Create two submission forms and apply them to pages on automatedlogistics.com. 

One for positive responses and one for negative responses. Use a URL format that can be added to email messages as a hyperlink.

This is the text from the client: 

Here are the questions, so all text fields.

```
Positive:

Is there an ALS team member who is Beyond Driven that you would specifically like to recognize? (Insert name or names) and describe how they are Beyond Driven:

 

Any suggestions on ways that we can improve upon our service or product?  

 

A box for these items and note that they are optional:

Name              Company Name               Email address:

 

And then a statement like: Thank you for providing us with your input – we genuinely care!

 

 

Negative:

Thank you for letting us know we are not delivering service that is Beyond Driven, which is our commitment to you. 

 

Please share why you are dissatisfied:

 

What can we do to improve our service or products?

 

Would you like immediate follow up from our leadership team? If yes, please include your contact information:

 

A box for these items and note that they are optional:

Name              Company Name               Email address:
```

**Comment by d4mation** [comment]
@lsextonALS If Email Address is an Optional Field, then the "Reply-To:" header of the Email cannot be populated. That means that you cannot just hit the "Reply" button when it hits an Email Inbox to reply to the person who filled out the form.

If they fill out the Email Address I can have the Email Address added into the Message Body, but without the Email Address Field being Required I cannot make a quick "Reply-To" work. Should the Email Address Field instead be made to be Required?

**Comment by d4mation** [comment]
Also, are there any additional user accounts that should be created that will have access to viewing the "In-Dashboard" Inbox?

![image](https://user-images.githubusercontent.com/7770631/36736947-d77f9070-1ba7-11e8-86d7-47d4c734b8d5.png)

**Comment by lsextonALS** [comment]
The reason for having the email address field be optional was in case anyone wanted to give feedback anonymously.  If that field remains optional but a statement like "if you would like us to get back with you, please include your email address" is included would that work, or are you saying that would create issues with all feedback responses?

In terms of having access to the inbox, we would like Joe Parker, Matt Eckler, Paul McDonald and Erica Wertanen to be included.  Let me know if you need any information to do that (email, etc)

**Comment by d4mation** [comment]
> or are you saying that would create issues with all feedback responses?

Yes, that would create issues with all feedback responses. Either it is a required field and the "Reply-To" functionality works, or it isn't a required field and if you were to reply to the Email, you would need to update the Email Address that you're replying to manually by copying the Email Address from the Message Body.

> we would like Joe Parker, Matt Eckler, Paul McDonald and Erica Wertanen to be included

I would need all of their Email Addresses, please. I will create them accounts on the website and once that is done, they should receive Emails with instructions to create a password.

**Comment by lsextonALS** [comment]
I spoke with the team and they are good with having to manually copy the email address for the sake of letting customers give feedback anonymously, so that can stay an optional field.

Below are the email addresses but before you create accounts for them, does that mean all four will receive the feedback messages?  Only Erica should receive these messages, but we'd like for the other three to have the ability to see messages in the inbox should they choose to do so (if possible).
jparker@automatedlogistics.com
meckler@automatedlogistics.com
pmcdonald@automatedlogistics.com
ewertanen@automatedlogistics.com

**Comment by d4mation** [comment]
Only Erica will actually receive the messages, but everyone else will be able to view a copy of the filled out Customer Satisfaction Surveys by logging in and clicking the "Inbox" link in the Admin Menu.

I'll get those accounts created :+1:

**Comment by lsextonALS** [comment]
Just a few changes: 
On the positive page, can a text field be added at the top with "What did we do well today?"
On the negative page, "Please share why you are dissatisfied" doesn't have a field to type in.  Also, can a check box be added to "Would you like immediate follow up..." The reason for this is so that customers don't think they can only leave their contact info if they want follow up.

**Comment by BigActual** [comment]
- [x] On the positive page, can a text field be added at the top with "What did we do well today?"

- [x] On the negative page, "Please share why you are dissatisfied" doesn't have a field to type in. 

- [x] Also, can a check box be added to "Would you like immediate follow up..." The reason for this is so that customers don't think they can only leave their contact info if they want follow up.

**Comment by BigActual** [comment]
@lsextonALS Please verify that I've completed the changes correctly?
- http://automatedlogistics.com/customer-satisfaction-survey-positive/
- http://automatedlogistics.com/customer-satisfaction-survey-negative/

Thanks,
Steve
