### ISSUE TITLE
Homepage timeline

### ISSUE THREAD

**Issue by lsextonALS** [automatedlogistics/Theme2016#109]
@d4mation We would like to add a block above the covenant on the homepage with videos for each.  Currently I can't add a video/hyperlink images on any blocks after the first item on the timeline.  Is this possible to do?

![image](https://user-images.githubusercontent.com/22197968/36562780-015a2e66-17e6-11e8-949a-8b367aa8c9ea.png)

**Comment by d4mation** [comment]
When editing the Home Page, if you click the little "+" that shows on the right-hand side you can insert Timeline Elements inbetween two other ones.

![image](https://i.imgur.com/qMsrfpT.gif)
