### ISSUE TITLE
Page doesn't show on web

### ISSUE THREAD

**Issue by lsextonALS** [automatedlogistics/Theme2016#110]
@d4mation I published this page with the Customer page as the parent, however it's not showing up on the website.
http://automatedlogistics.com/customers/als-3pl-solutions/

**Comment by d4mation** [comment]
That link works for me. Are you expecting it to show in a menu? The menus are not automatically generated.

**Comment by lsextonALS** [comment]
Yes, I'd like it to show as a drop down under Customers, like the About Us tab.

**Comment by lsextonALS** [comment]
In addition to having this showing as a drop down option, would it also be possible to for the 3pl icon on the customers page to link to this page (so the new page would completely replace the current 3pl page)?

**Comment by d4mation** [comment]
All set :+1:
