### ISSUE TITLE
Staff Single Template

### ISSUE THREAD

**Issue by d4mation** [automatedlogistics/Theme2016#12]
> As I understand it, the information required here includes presentation of LinkedIn link, a bio, an image, and what else?
- Photo
- Full name (plus nickname … which humanizes each person)
- Brief professional bio
- Contact links (email, social links, etc.) (recommend to ALS that all employees should have LinkedIn accounts)
- Brief personal bio (again, the neighbor begs to be seen as approachable) 
  - We could even have fun with this one; Every now and again, we add a new ‘tid bit’;  Favorite quote, favorite food, favorite color, favorite song/musician, etc.

**Comment by BigActual** [comment]
I'll go to the client with this request today. Please use placeholders in the meantime.
