### ISSUE TITLE
Other “non-page” content

### ISSUE THREAD

**Issue by d4mation** [automatedlogistics/Theme2016#13]
- [ ] Concepts for CTAs that can go ‘inline’ with page content (e.g. “Call us Today to Get Started” … or “Sign up for our Newsletter”)
- [ ] Rotating Testimonials
- [ ] Rotating Industry Tips
- [ ] Rotating “Featured Client”
- [ ] Rotating “Featured Service Rep”

**Comment by BigActual** [comment]
Any reason to keep this open?

**Comment by d4mation** [comment]
Not particularly. I just pulled this from that Google Doc with all the content in it. Figured if needed, it was here for discussion.
