### ISSUE TITLE
Base Images for Main Image and Footer Hero

### ISSUE THREAD

**Issue by d4mation** [automatedlogistics/Theme2016#15]
I'm setting the site up so that the text and button are HTML elements rather than being embedded into the image for accessibility reasons (screen-readers, more responsive for mobile, etc.). Right now it is overlapping and doesn't look so great. 

![image](https://cloud.githubusercontent.com/assets/7770631/14117792/3fd2c8de-f5b4-11e5-9ff7-c576586c0291.png)

Also, the ZIP you sent Kyle didn't include the Image toward the bottom of the Home Page from what I could tell.

![image](https://cloud.githubusercontent.com/assets/7770631/14117849/931cd5c0-f5b4-11e5-811b-c59c3b2a8e7d.png)

Could you send the original images for these my way, please?

**Comment by skarritt** [comment]
Hi,  The main hero image will be sent to you "sans text and sans button" in just a bit.  Please hold off on the footer row (currently called "The Perfect Order").  It's going to be replaced by FOUR new rows, specifically for: Carriers, Shippers, Careers, The Covenant.  As soon as I get an approval on their design, I'll send them to you for integration into the home page.  Until then, proceed without.
Let me know if this isn't clear.

**Comment by skarritt** [comment]
Here you go.
Kevin

Kevin Skarritt
Chief Peep, Flock Marketing
PO Box 126, Grand Ledge, MI 48837
517-925-8045
@skarritt
facebook.com/flockmarketing
linkedin.com/in/skarritt

=-=-=-=-=-=-=-=-=-=

This message has been brought to you by the numbers 1 and 0!

**Comment by d4mation** [comment]
Sadly, attaching files to GitHub via reply-email doesn't work. :/

You can send them to me via my work email eric@realbigmarketing.com if that works for you. Otherwise, I'm pretty sure you can upload files to the Issue if you are on GitHub via a web browser.

**Comment by skarritt** [comment]
Sorry about that.  Here it is ... again.
![home-main-image-1bkg](https://cloud.githubusercontent.com/assets/13339771/14141914/388916ea-f650-11e5-9a84-874bae1205cd.jpg)

**Comment by d4mation** [comment]
Thanks! Looks great in my local environment now.

Let me know when you've got approval on those new sections!

**Comment by skarritt** [comment]
Will do.

**Comment by BigActual** [comment]
Had Kevin sent you the 4 images he mentioned above?

**Comment by d4mation** [comment]
Nope. I'll open another Issue for that real quick.
