### ISSUE TITLE
Footer suddenly isn't working properly

### ISSUE THREAD

**Issue by d4mation** [automatedlogistics/Theme2016#16]
Large portion of the Footer is missing without PHP Errors or JavaScript Errors.

This is going to be an adventure.

**Comment by d4mation** [comment]
What's even stranger is that this seems to only happen in Production. Locally everything is fine.

**Comment by d4mation** [comment]
Ugh, that's embarrassing.

Browser extension was hiding it. Must have updated some of its rules to include the majority of the footer.

**Comment by BigActual** [comment]
Nice.
