### ISSUE TITLE
Shippers Landing Page

### ISSUE THREAD

**Issue by d4mation** [automatedlogistics/Theme2016#2]
Include Services [category:shipper] Archive Loop
- [ ] Elevator Pitch
- [ ] List of benefits to Shippers
- [ ] List of services and service features
- [ ] Why we’re different
- [ ] Case studies (mega-expanded testimonial)
- [ ] Mini-CTAs throughout this long page
- [ ] Meet your Rep section (maybe a carousel of photos with name underneath)
- [ ] BIG “Get Started” CTA  at bottom

**Comment by d4mation** [comment]
@BigActual 

I know the plan is to write up a lot of it later and place it in, but I want to ensure that I’ve got places for them to do that.

It seems like they are going to want a lot of more complicated sections on this page that wouldn’t be easy to implement through the standard Editor. At the same time, I’m not sure what to anticipate to code something out for them. 

Could get some samples/examples from them for that?

**Comment by BigActual** [comment]
We'll be developing that content over the next several weeks. The client and Kevin are on vacation until the 11th. I will, however ask the writer (Nancy) to draft up the first iteration of one of these.

**Comment by d4mation** [comment]
I ended up handling this and #18 the same for now.

The implementation for now is identical to the Services Page (#9), but they are limited to their respective Categories.

This allows content to be easily placed above or below the Services Listings. I closed #18, but seeing as these pages may be very similar in terms of implementation, I'm going to leave this Issue open for now.

**Comment by BigActual** [comment]
I'd like to pitch in and help here Eric. Could you clarify the question for me pleae?

**Comment by d4mation** [comment]
I pulled the checkboxes above at the start of the Issue from some bullet points in the Google Doc.

I'm just looking for specifics on how they want those kinds of things implemented, as they are likely going to be too complicated to be thrown directly into the standard, default content editor. Even a simple-mockup describing what they are wanting it to look like would help because then I can determine how to most efficiently create a way for that information to be added to the site.

As it stands now, I grabbed the content from the Google Doc that has been typed up and placed it into the page. If that's all they are looking for, that's fine. The CTAs and stuff just sound like they will need their own fields to be easily added into the Page Content. I want to be sure I can provide them with what they need.

![image](https://cloud.githubusercontent.com/assets/7770631/14467661/57de2936-00aa-11e6-9e25-5c7a2377d9e0.png)

(Services with the "Shipper" category also display below this area on the Page.)

**Comment by BigActual** [comment]
@skarritt and i have a conversation scheduled at 11am tomorrow, the 13th, to discuss this.

**Comment by d4mation** [comment]
Any updates on this? @BigActual @skarritt

**Comment by BigActual** [comment]
We're trying to connect.

**Comment by BigActual** [comment]
OK, so here's the deal. Finish what was laid out in the mockup and these items are what we're going to employ later. So, for now. Finish and prepare to add as required in the future.

**Comment by d4mation** [comment]
I have all the screenshot mockups (#7, #3, and #9) all taken care of. 

I've added the content from the Google Doc to the Page in the Content Editor, so all that's really left for this page would be the Checkboxes above.

I'll close this Issue, and we'll make new Issues for the other items as-needed then.
