### ISSUE TITLE
Lack of contact us form

### ISSUE THREAD

**Issue by BigActual** [automatedlogistics/Theme2016#21]
Lack of Contact us form on the Connect page seems wonky. Would like to add it. @skarritt  Where do you want to put it?

**Comment by skarritt** [comment]
Either of two options:

1) Have only one "Connect" page and put the info into priority order:
      - intro blurb
      - main contact info (Joe's info for now)
      - contact form
      - credit app
      - job app info

OR...
2) Have separate forms for "Connect", "Credit App" and "Job App" functions.

my 2¢

**Comment by BigActual** [comment]
Separate seems more intuitive for the end user. If connected to the
workflow for each process.

On Wed, Apr 13, 2016 at 4:15 PM, Kevin Skarritt notifications@github.com
wrote:

> Either of two options:
> 
> 1) Have only one "Connect" page and put the info into priority order:
> - intro blurb
> - main contact info (Joe's info for now)
> - contact form
> - credit app
> - job app info
> 
> OR...
> 2) Have separate forms for "Connect", "Credit App" and "Job App" functions.
> 
> my 2¢
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/automatedlogistics/Theme2016/issues/21#issuecomment-209627689

## 

Thanks,

Steven R. Bennett, Partner
Real Big Marketing, LLC.
(517)358-6794

---

THIS MESSAGE IS CONFIDENTIAL. This e-mail message and any attachments are
proprietary and confidential information intended only for the use of the
recipient(s) named above. If you are not the intended recipient, you may
not print, distribute, or copy this message or any attachments. If you have
received this communication in error, please notify the sender by return
e-mail and delete this message and any attachments from your computer.

**Comment by d4mation** [comment]
Just to clarify:

Is the idea to have 3 separate Forms on the same Page, or to have 3 separate Pages holding individual Forms? Either way works.

I must have not accounted for one originally after seeing this on the Google Doc as I was creating Issues. I guess I interpreted it as "no forms" even though a Contact Form is pretty important.
![image](https://cloud.githubusercontent.com/assets/7770631/14509998/47987632-019d-11e6-81f2-b00c10200136.png)

Adding a space within the Page Template to select Forms to add wouldn't be a problem at all.

**Comment by brashrebel** [comment]
I was mistaken. A very simple contact form is within scope for phase 1. Please add one.

**Comment by d4mation** [comment]
Just added it to the Page Template with an ACF control. This way it can be easily swapped out if needed.

![image](https://cloud.githubusercontent.com/assets/7770631/14570224/23a46770-0311-11e6-8cfe-8d0b406575b1.png)

![image](https://cloud.githubusercontent.com/assets/7770631/14570237/34a25ec4-0311-11e6-825f-b7a743aecdcf.png)
