### ISSUE TITLE
home page bottom border

### ISSUE THREAD

**Issue by JasonWebsterALS** [automatedlogistics/Theme2016#24]
On my pc, the home page has a white bottom border and I think it would be cool if there was an icon in the middle of that border telling people to scroll down. I've seen something similar on website and it was a translucent type icon that disappeared as I started to scroll but would appear again when I stopped. I think this could help users know there is more content below.

**Comment by d4mation** [comment]
I've mocked something up for this within another branch of code on my own computer. Here's a quick .GIF of it in action.

At the start you can see that as I scroll down, the Arrow fades out of sight. However, if I decide to click on the Arrow, it smoothly scrolls me down to the Timeline area.

(On my local copy of the site, I don't have the Menu above including all the Links that you can see on the Test Site)

![image](http://i.imgur.com/5YDfg5e.gif)

What do you think? Different screen resolutions will crop the page at different parts, unfortunately. I can barely see the first "dot" on the Timeline on my laptop and on my desktop I believe I can see even more of it.

For mobile, I set the Arrow to show higher up on the page for this reason:

![image](https://cloud.githubusercontent.com/assets/7770631/14785403/969fd5a2-0ac8-11e6-8f57-64da5822321d.png)

**Comment by JasonWebsterALS** [comment]
I think it looks good.

Thanks,

Jason Webster
Inside Sales Executive
Office +1 800.551.9399 x 168
Mobile +1 517.974.9230
Fax +1 517.905.3102

   “Delivering Experiences with Passion and Energy”

[cid:image001.jpg@01D0C9DF.0D727800]http://www.automatedlogistics.com/
AfterHours@automatedlogistics.commailto:AfterHours@automatedlogistics.com is available 24/Hours for assistance.

Disclaimer: All services by Automated Logistics are subject to the terms and conditions at www.automatedlogistics.com/terms.htmhttp://www.automatedlogistics.com/terms.htm

**Comment by BigActual** [comment]
I'm sorry I was out of town and wasn't able to address this. The scroll down function was left out on purpose. The red button takes away from the actual call to action which is the three buttons that sit right above it. That's the course of action we want end users to follow. Everything below is important, but mainly for SEO purposes and for the minority of users who don't go in the direction we're planning for them. 
to paraphrase @skarritt, the home page is like a room full of monkeys and we want to dangle very few bananas.  Please pull that button out for now. No disrespect to you @JasonWebsterALS. We have plans to test the UX after launch. If the data shows that we need to change, it's on the top of the list.
