### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by JasonWebsterALS** [automatedlogistics/Theme2016#25]
When I go to the bottom of the home page and click "our services" and go to that list, if I select one, there isn't an easy way to go back to the list. It would be nice if there was back button somewhere once you selected to learn about one of our services that would take them back to the page where they are all listed. I could get back by selecting our services again at the bottom of the page, so that may suffice but if the content pushes the bottom of the page down some, the back button may be nice.

**Comment by d4mation** [comment]
![image](http://i.imgur.com/uBPm1Jt.gif)

I've decided to implement this as "Breadcrumbs" throughout the site so that Users can easily follow their trail back to where they were before without needing to rely on the Back functionality within their Web Browser.

Does this line up with what you're looking for?

**Comment by JasonWebsterALS** [comment]
Yes. It is better than what I was hoping for.

Thanks,

Jason Webster
Inside Sales Executive
Office +1 800.551.9399 x 168tel:+1%20800.551.9399;168
Mobile +1 517.974.9230tel:+1%20517.974.9230
Fax +1 517.905.3102tel:+1%20517.905.3102

 Automated Logistics Systems

   "Delivering Experiences with Passion and Energy"

On Apr 25, 2016, at 11:27 AM, Eric Defore <notifications@github.com<mailto:notifications@github.com>> wrote:

[image]https://camo.githubusercontent.com/97d24869d9f53ccae57489880a3821d6baa9455d/687474703a2f2f692e696d6775722e636f6d2f7542506d314a742e676966

I've decided to implement this as "Breadcrumbs" throughout the site so that Users can easily follow their trail back to where they were before without needing to rely on the Back functionality within their Web Browser.

Does this line up with what you're looking for?

##
