### ISSUE TITLE
Right Sidebar with widgets for Shippers Page

### ISSUE THREAD

**Issue by BigActual** [automatedlogistics/Theme2016#32]
Call us today
Phone number

Contact Us

**Comment by brashrebel** [comment]
Do you have any guidance for how these should look? Are these in the mockups?

**Comment by BigActual** [comment]
Kevin's swamped. To make it faster, would @d4mation use his best judgement and let us suggest edits please?

**Comment by brashrebel** [comment]
I don't really like that normally because it's slower but this is a fairly simple element so I'm ok with it.

**Comment by BigActual** [comment]
Thanks
