### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by skarritt** [automatedlogistics/Theme2016#33]
It feels "odd" to have the first block of text on this page being about a "credit application". This seems more like it should be on the shippers/carriers pages.

Also, the block with Joe's contact information without any message from Joe (something like, "You're important to us. Feel free to contact me directly. Joe") feels a little off.

If this doesn't make sense, please contact me -- 517-925-8045

**Comment by brashrebel** [comment]
Yeah, that makes sense. But it is a content question so we'll need to get the content people in the discussion. That page content is editable and we can certainly rearrange. We just need concrete, final direction to do so.

**Comment by BigActual** [comment]
I'll have Nancy address this. Assigning to me. Will mark complete when done.

**Comment by BigActual** [comment]
Addressed in #68
