### ISSUE TITLE
Employment Single Template

### ISSUE THREAD

**Issue by d4mation** [automatedlogistics/Theme2016#4]
General for now. Job Description. Use Contact Us form for now.

Contains:
- Job Title
- Job Description
- Not sure what other fields are required for MVP.
- Salary range
- Experience required
- Travel requirements

**Comment by BigActual** [comment]
This is on hold. It was an assumption on my part which Kyle clarified would come later. Also, Employment Opportunities are being addressed in #3. Recommend close.

**Comment by d4mation** [comment]
That's what I was thinking too. Especially since, at least based on the what I could see in the screenshot of the mock-up, all the information fits pretty easily.

Here it is on my local install:
![image](https://cloud.githubusercontent.com/assets/7770631/14146680/83ca4eb0-f666-11e5-996f-7b8b68b8e917.png)

I'll go ahead and close this for now.
