### ISSUE TITLE
left justify search button

### ISSUE THREAD

**Issue by BigActual** [automatedlogistics/Theme2016#40]
![image](https://cloud.githubusercontent.com/assets/8271108/14998222/dcfc0cbc-1150-11e6-96d3-3120f32e4472.png)

**Comment by d4mation** [comment]
To clarify, you're wanting it aligned to the right? I always think of justification in the typographical sense in that the left and right edges of a block of text are as flat as possible and larger spaces between words may be needed to achieve it. 

![image](https://cloud.githubusercontent.com/assets/7770631/15014202/a1a5c888-11d2-11e6-98af-5d11eccca932.png)

**Comment by BigActual** [comment]
aligned left

**Comment by d4mation** [comment]
Ah, I see what's happening in your screenshot now. I thought you had gone into the inspector and aligned it to the right, but it is just the way the image is cropped.

Pushing changes now.
