### ISSUE TITLE
Careers Page - Present page with all jobs closed

### ISSUE THREAD

**Issue by BigActual** [automatedlogistics/Theme2016#41]
http://alsintersite11.wpengine.com/careers/
![image](https://cloud.githubusercontent.com/assets/8271108/14999067/f559fb44-1154-11e6-8d46-2ab8d5c0bdd7.png)

**Comment by brashrebel** [comment]
same as #29

**Comment by BigActual** [comment]
Ha ha, yes. We were collaborating.
