### ISSUE TITLE
Global Change Shippers to Customers

### ISSUE THREAD

**Issue by BigActual** [automatedlogistics/Theme2016#42]
SItewide, please change all instances of the Titles, Links and Buttons using the word Shipper, to Customer and Shippers to Customers. Thanks

**Comment by d4mation** [comment]
I've gone through and changed any and all references to "Shipper" to "Customer" within the source code.

On the "Customers" page (Used to be "Shippers") there are still instances of the word "Shipper" as it seems to make better sense in-context in some parts of the copy. If needed, this can be easy changed.
