### ISSUE TITLE
Adjust the method with which clicking [Find Out How] in the hero image displays content.

### ISSUE THREAD

**Issue by BigActual** [automatedlogistics/Theme2016#43]
When you click on “Find out How” under Beyond Driven it will display an overlay that looks similar to the search overlay. 
The covenant video will show here which is being created by JTV. There will still be Customer, Carrier, and Careers Icons available for people to take the next step after hearing the info, just like on the home page.
I suggest placing those underneath the video so they align similarly with what's underneath the overlay on the home page.

**Comment by BigActual** [comment]
Call me to discuss this Eric.

**Comment by BigActual** [comment]
Use this file while the videographers figure out how to get back the youtube channel: https://youtu.be/kypHrk2_wK4

**Comment by d4mation** [comment]
Minor tweaks and then this will be all set. I'm making the video URL a Field that can be updated at any time within the Home Page Edit Screen.

![image](https://cloud.githubusercontent.com/assets/7770631/15608920/df3d8e5e-23ea-11e6-963d-eec0583c8626.png)
