### ISSUE TITLE
Create and Style Blog as ALS News and create links from home page to content

### ISSUE THREAD

**Issue by BigActual** [automatedlogistics/Theme2016#44]
Create and style Blog Post Type, and related templates. Client would like to call this section ALS News.
Create three links from the home page: Main Navigation, Repurpose the “XXXX” blank space in the Red Line to show the latest post or video, and footer nav link. Within this section ALS will post things like quarterly meeting updates and blog posts ghost written by interns.

@brashrebel, I understand this to be a 1.1 item, not to hold back launch so let's put together the project now and ensure that appropriate parties are working on artwork.

**Comment by d4mation** [comment]
Using some Filters, we should be able to re-purpose the built-in "Posts" Post Type to do this. That way we can slim down Database requests and prevent there being an empty, not used section in the backend. Overall things would be more efficient for the website and the client.

From there, implementation would be exactly the same as we've talked about for this. (Being able to show YouTube video thumbnails as the featured image, etc.)
