### ISSUE TITLE
Carriers Packet Download (PDF File)

### ISSUE THREAD

**Issue by BigActual** [automatedlogistics/Theme2016#46]
On the “Carriers” page have a place to download carrier packet pdf 

I've requested a copy from the client. Will post here when available

**Comment by BigActual** [comment]
Have requested a copy of this from the client. Shouldn't hold up launch however it's important.

**Comment by BigActual** [comment]
https://mail.google.com/mail/u/0/?ui=2&ik=f80daacdb5&view=att&th=154ed093e78b5483&attid=0.1&disp=inline&safe=1&zw

**Comment by BigActual** [comment]
@d4mation Can you pull that linked pdf to your lappy?

**Comment by d4mation** [comment]
Might need to upload it straight to the Issue.

![image](https://cloud.githubusercontent.com/assets/7770631/15578469/8e8bceba-232e-11e6-9fce-f92517e0ed1f.png)

**Comment by BigActual** [comment]
[ALS_Carrier_Packet.pdf](https://github.com/automatedlogistics/Theme2016/files/284629/ALS_Carrier_Packet.pdf)
 Under the call to action on the right side. A nice looking adjustment to the sidebar. It's sad and needs a touch up.

**Comment by d4mation** [comment]
It looks like it has already been added in:

![image](https://cloud.githubusercontent.com/assets/7770631/15649206/dba0c612-263d-11e6-8718-5db4dca53c40.png)

We could adjust the Header Sizes/Button Sizes of the CTAs, but aside from that I'm not sure what else we could do for that section while preserving the flexibility of that section. Implementing fields specific to a certain CTA would likely backfire further down the line when things are needing to be changed again.

**Comment by BigActual** [comment]
I'd like each CTA to be visually separate from the one above it. Some way to separate these into separate boxes of content

**Comment by d4mation** [comment]
I see. Something like this then? It will automatically separate each one into a new block.

![image](https://cloud.githubusercontent.com/assets/7770631/15674731/62e63b7e-270c-11e6-84d2-07652a6b4228.png)

![image](https://cloud.githubusercontent.com/assets/7770631/15674750/7473d086-270c-11e6-8563-2210a8b16c49.png)

**Comment by BigActual** [comment]
Yes
