### ISSUE TITLE
Staff Single Template

### ISSUE THREAD

**Issue by BigActual** [automatedlogistics/Theme2016#48]
[Profile Master.docx](https://github.com/automatedlogistics/Theme2016/files/268800/Profile.Master.docx)

See page 1

**Comment by BigActual** [comment]
Please format to match, any oddities in design should default to the existing web standards. I.e. Font sizes, lines, etc. The portrait does not have any lines around it and needs to be resized to match the ratio of the pic presented in the Word Doc.

**Comment by BigActual** [comment]
Also, please make sure the the editor will have fields to enter social media profile links. LinkedIn is required.

**Comment by BigActual** [comment]
Earlier in the thread, I spec'd that page 2 was the profile layout to reference. That's incorrect. Use the one marked Online Profile in the Word Doc.I've changed that comment to match.

**Comment by brashrebel** [comment]
I like the profiles. I do think that the icons could potentially be improved by adding some text, possibly below each one. I don't believe the icons are explanatory enough on their own without some accompanying text. Also, on that note, we will need a comprehensive list of the icons that need to exist and the description/label for each so we can make them available. Probably a group of checkboxes?

**Comment by BigActual** [comment]
The icons, as awards, don't even exist as more than a forethought. Placeholder information. Not even the right icons. They're just ones I scraped from the web. No plan on how to address that section. Need your input to help define the process @brashrebel .

**Comment by BigActual** [comment]
To set the stage however, the Managers are giving the staff a corkboard and the GEM (Going the Extra Mile) Award is basically a thank you card with a round pin that can be stuck in the board. Badges of honor like football players wear on their helmets. The buttons will be pre-printed and handed out individually. They are not defined yet either.

**Comment by BigActual** [comment]
With regard to your request for text. I don't know that they're important enough to highlight that way. I'd suggest just adding text that shows up on hover, like the name of the award.

**Comment by brashrebel** [comment]
Ok. I'm alright with that. Although we can't incorporate it at all until we have the labels and visuals. Ok to omit those for now and open a separate issue to add them once they actually exist?

**Comment by BigActual** [comment]
Sounds appropriate to me as well.

**Comment by BigActual** [comment]
Call me to discuss the details of this Eric.

**Comment by BigActual** [comment]
[Profile-Master-V2.pdf](https://github.com/automatedlogistics/Theme2016/files/284656/Profile-Master-V2.pdf)

**Comment by BigActual** [comment]
For the badges, create some dummies for use as placeholders as the client comes up with their own. 55px \* 55px. Make it a field for uploading the icon and a field for the very short description so that, on hover, the description shows like a tool tip.

**Comment by d4mation** [comment]
![image](https://cloud.githubusercontent.com/assets/7770631/15582741/80f204c4-2340-11e6-8f59-18baa4cb5bca.png)

Are there intentions to include staff members that no longer work with ALS? Just curious since the Date Range seems a little strange.

**Comment by BigActual** [comment]
In my mind is was simpler to comprehend this than to have to read the words "Start Date:" Plus that would have blown out my simple icon alignment.

**Comment by d4mation** [comment]
Ah, I see. That makes sense. I've got `— Present` hardcoded in there for now to go after the date value.

All that's left for this Issue is getting those Badges looking nice.

**Comment by d4mation** [comment]
In the mockup it looks like the Name is meant to be a banner, so I've implemented it as such. The Breadcrumbs get orphaned a bit that way, but the only way I could think to integrate them would be to put them to the right inside the "Name Banner" and I didn't want to move an otherwise static element for just this template.

Badges get scaled down to fit either `55px` width or height&mdash;whichever it hits first. 

The Phone Number's `tel:` link should automatically dial the extension on both iPhone and Android, which is a nice little extra.

Pushing changes to the test server now. Issue will be Closed once the files are up. I need to add some extra Fields on the Test Site for everything to work for this.

![image](https://cloud.githubusercontent.com/assets/7770631/15587205/2ee55526-2356-11e6-8c53-8d03748461ee.png)

**Comment by BigActual** [comment]
I like it better without the blue bar.

**Comment by d4mation** [comment]
Removed the blue banner 👍
