### ISSUE TITLE
Logo fuzzy on retina

### ISSUE THREAD

**Issue by joelworsham** [automatedlogistics/Theme2016#51]
Can you double the resolution of the image for the main header logo? It's fuzzy for me (retina)

**Comment by d4mation** [comment]
Is there a larger resolution of the logo in the header available, @skarritt?

If you can provide an .SVG/.EPS, we can scale it up to whatever size we need without losing quality.

**Comment by joelworsham** [comment]
Low resolution on retina logos are one my biggest pet peeves on websites. It's nit picky I know, but it's like the first thing I notice ;)

**Comment by BigActual** [comment]
[LOGO-TAG-MASTER-WHITE.zip](https://github.com/automatedlogistics/Theme2016/files/272697/LOGO-TAG-MASTER-WHITE.zip)

**Comment by skarritt** [comment]
Joel, Here's a PNG if Steve's zip file doesn't do it for you.
![logo-main-retina](https://cloud.githubusercontent.com/assets/13339771/15432832/d3147010-1e7d-11e6-8f52-1fb3551cd1f8.png)

**Comment by d4mation** [comment]
Just swapped it out for that .PNG and it looks much more crisp.

@joelworsham, how does it look on your end? Could be placebo, but I flipped between the test site and my local install and I think it looks significantly better now.

**Comment by joelworsham** [comment]
MUCH better. 👍
