### ISSUE TITLE
Staff Page Template

### ISSUE THREAD

**Issue by BigActual** [automatedlogistics/Theme2016#52]
Paul indicated that he likes this flipping idea for the ALS Staff Page Template. Up for discussion is: http://locallogicmedia.com/team.php

**Comment by BigActual** [comment]
Call me Eric to discuss this  idea.

**Comment by owielanctot** [comment]
YES- this is fantastic. If we can do this I think we should. What the example doesn't have that we need keep from our current format is contact info for each person

**Comment by BigActual** [comment]
It is fun isn't it. Kyle has this in the cue for discussion along with several other things that Paul asked for earlier on. Enhancing sites is always the fun part.
