### ISSUE TITLE
Content for Carriers page

### ISSUE THREAD

**Issue by owielanctot** [automatedlogistics/Theme2016#53]
[Carriers.docx](https://github.com/automatedlogistics/Theme2016/files/278206/Carriers.docx)

@BigActual

**Comment by BigActual** [comment]
Thanks @owielanctot . I've uploaded the copy and will adjust this week. Will place a note here when ready for your review.

**Comment by BigActual** [comment]
Updated for review. Please advise @owielanctot

**Comment by owielanctot** [comment]
[Carriers edit.docx](https://github.com/automatedlogistics/Theme2016/files/302749/Carriers.edit.docx)

Changes are highlighted in the document.

**Comment by BigActual** [comment]
@d4mation , please remove the copy from the bottom of the content area, "No Carrier Services Found". I suspect you have a snippet in the background looking for services to be listed here. However, services will show up on /customers/ , not here.

**Comment by d4mation** [comment]
Indeed I did&mdash;I think that was specced out in the old Google Docs Content for the page back when I created the Page Template. I've just removed it, changes are up on the test server now.
