### ISSUE TITLE
Content for Careers page

### ISSUE THREAD

**Issue by owielanctot** [automatedlogistics/Theme2016#54]
[Careers.docx](https://github.com/automatedlogistics/Theme2016/files/278208/Careers.docx)

@BigActual

**Comment by BigActual** [comment]
Uploaded to site @owielanctot . Will advise here when ready for your review.

**Comment by BigActual** [comment]
I've integrated the new copy creating a hybrid @owielanctot. Please let me know what you think.

**Comment by BigActual** [comment]
Per our conversation today @owielanctot, I'm marking this complete. Let's create new tickets for new ideas on this page.
