### ISSUE TITLE
Content for ALS staff page

### ISSUE THREAD

**Issue by owielanctot** [automatedlogistics/Theme2016#55]
Working with ALS means you’re part of a family – not a corporate hierarchy.    Our people are at the core of our success.  We firmly believe the best investment you can make is in your people.   The ALS commitment to talent is evident in each individual you work with on a daily basis and in the teams that will tackle the most complex solutions.  We are dedicated to hiring and developing the smartest supply chain professionals the industry has to offer.      

The family approach runs deep in our culture and is evident in the way that we interact with our co-workers, vendors, and customers.   We have a genuine care for one another, and a competitive drive that moves us forward.   This personal touch combined with an unwavering commitment to operational excellence is what truly sets us apart.  

@BigActual

**Comment by BigActual** [comment]
Uploaded to site. Will let you know here when it's ready for review, @owielanctot .

**Comment by owielanctot** [comment]
[Careers Edit.docx](https://github.com/automatedlogistics/Theme2016/files/304762/Careers.Edit.docx)

Just two small edits here

**Comment by BigActual** [comment]
Yeah, that period outside the " is a European thing I picked up somewhere in my travels. Done.
