### ISSUE TITLE
Create a Favicon and add to site, using the logo

### ISSUE THREAD

**Issue by BigActual** [automatedlogistics/Theme2016#57]

**Comment by BigActual** [comment]
[LOGO-SVG.zip](https://github.com/automatedlogistics/Theme2016/files/284594/LOGO-SVG.zip)

**Comment by d4mation** [comment]
![image](https://cloud.githubusercontent.com/assets/7770631/15581331/d1cf63c0-2339-11e6-82fa-cc2e279d8752.png)

On anything older than IE 11 it seems Microsoft only added support for `16x16` Favicons so it looks a bit scrunched.

Looks great on Firefox and Chrome though. [Safari strangely removed support for displaying Favicons at some point which made a lot of people angry.](https://discussions.apple.com/thread/6601441?tstart=0)

**Comment by BigActual** [comment]
Safari 5.1.7 for Windowns still carries the favicon. Just an FYI.

**Comment by d4mation** [comment]
Hmm, interesting. The Windows version of Safari was discontinued so that's the final version available technically. I'd hope people wouldn't use such an old version, but at least the Favicon works 🙈
