### ISSUE TITLE
Content for Customers page

### ISSUE THREAD

**Issue by owielanctot** [automatedlogistics/Theme2016#58]
[Customers.docx](https://github.com/automatedlogistics/Theme2016/files/285140/Customers.docx)

@BigActual

**Comment by BigActual** [comment]
Thanks. I'll upload and merge.

**Comment by BigActual** [comment]
Merged and ready for review @owielanctot

**Comment by owielanctot** [comment]
[Customers edit.docx](https://github.com/automatedlogistics/Theme2016/files/304689/Customers.edit.docx)

Eidts for Customers page. Including further breakdown of products/services

**Comment by BigActual** [comment]
Updated
