### ISSUE TITLE
Remove border around image and scale the image to match the layout from the provided file

### ISSUE THREAD

**Issue by BigActual** [automatedlogistics/Theme2016#59]
![image](https://cloud.githubusercontent.com/assets/8271108/15588881/19b84dae-235e-11e6-8dc7-811a33558260.png)

Scale the image to match the original mockup provided in #48

**Comment by BigActual** [comment]
Just a sec, I'll crop that.

**Comment by BigActual** [comment]
![image](https://cloud.githubusercontent.com/assets/8271108/15588825/bd5fcb4a-235d-11e6-8fdf-92187643c7a4.png)

**Comment by d4mation** [comment]
The Mockup used photos that allow the full-height to be seen, so I adjusted the scaling to account for that.

"Find me on" text now aligns better as well to match up with the mock-up.

![image](https://cloud.githubusercontent.com/assets/7770631/15589521/43d072bc-2361-11e6-90d4-66fd1aca1e53.png)
