### ISSUE TITLE
Login Screen

### ISSUE THREAD

**Issue by d4mation** [automatedlogistics/Theme2016#6]
> Steve: "Simply needs to match the theme?"
> 
> Consideration for “existing registered user” vs. “new user”
> Are we allowing oAuth login?
> 
> Kyle: "I don't think there is any need for a login screen getting special attention in this phase. Only staff will use the site admin for a long time."

**Comment by BigActual** [comment]
Let's at least make sure the client logo is used here.

**Comment by d4mation** [comment]
The Logo is now in place for the Login Screen. It links to their website instead of wordpress.org as well.

![image](https://cloud.githubusercontent.com/assets/7770631/14460332/f3b24394-008a-11e6-9d8d-c35e9b975903.png)

**Comment by BigActual** [comment]
Nice.
