### ISSUE TITLE
Implement best method for handling /terms.htm 404

### ISSUE THREAD

**Issue by BigActual** [automatedlogistics/Theme2016#61]
Of course I'll ask the client to change their links for their terms from /terms.htm to /terms/ however, this is a mission critical page and I'd like to have a highly effective, zero error ever, redirect in place to handle this issue from day one. Open to alternative suggestions. This is not to ever create a 404.

**Comment by d4mation** [comment]
Where are they currently linking to `/terms.htm`? 

I can think of a few ways of handling this:
1. I can filter the output of each page to replace any links to `/terms.htm` to `/terms/` automatically. However, if a user manually navigates to `/terms.htm` (Say, it is in someone's e-mail signature) it would still 404.
2. I can throw a simple 301 Redirect into the `.htaccess` file. However, WP Engine _may_ attempt to interfere with that at some point by overwriting it with a "Last good backup" if they notice it got modified. I did make some modifications to the `.htaccess` for the RBW Multisite without issues though.
3. I can hardcode a redirect in the Theme for this use-case. This would ensure it always worked and it would be harder to forget about (in case it ever becomes a problem) having it directly in the source code.
4. We could implement a 3rd Party Plugin to handle it similarly to 3, but this would give us a nice user interface.

**Comment by brashrebel** [comment]
Handling redirects is a standard step in our process if we're re-launching a site. It's one of the last things we do but we always account for all _known_ URLs. Often we will request a list of URLs from a client or take it upon ourselves to compile a list of what we must handle which will probably be our action in this case.

As for implementation method, most often we'll handle them within WPE. But there are exceptions.

**Comment by d4mation** [comment]
I see, that makes sense. Never checked out the Redirect Rules section of WP Engine. That will work just fine.

Looks like here's what we'll need to work with (Unknown pages are marked as question marks):

`/index.htm` -> `/`
`/aboutus.htm` -> `/about-us/`
`/van.htm` -> ???
`/specialized.htm` -> ???
`/international.htm` -> ???
`/quote.htm` -> ???
`/terms.htm` -> `/terms/`
`/careers.htm` -> `/careers/`
`/contact.htm` -> `/connect/`

**Comment by BigActual** [comment]
This exists in all email signatures for the company. Thanks for the attention.

**Comment by BigActual** [comment]
@d4mation This is always helpful for me: https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=site%3Aautomatedlogistics.com

**Comment by d4mation** [comment]
Ah, looks like their mobile site was in a subdirectory. Going to need to ensure our redirect rules cover those as well.

**Comment by d4mation** [comment]
I just implemented some 301 Redirects for the above listed URLs (Including their Mobile counterparts). 

We'll probably want to figure out what to do for the ones I marked as question marks.

**Comment by BigActual** [comment]
Van, Specialized, International go to  /Customers/   ...for now. Specific services are in the works.
Quote goes to /connect/

**Comment by d4mation** [comment]
@BigActual Went ahead and made some redirects to those. For Van, Specialized, and International I made them `302 Redirects` rather than `301` since they are temporary 👍

**Comment by BigActual** [comment]
Any reason to keep this open?

**Comment by d4mation** [comment]
Only reason I could see to keep this open would be for the eventual paths of those temporary 302 Redirects.

Those can be made into a new Issue later though.
