### ISSUE TITLE
Replace testimonials

### ISSUE THREAD

**Issue by owielanctot** [automatedlogistics/Theme2016#63]
See Owie's email
@BigActual

**Comment by BigActual** [comment]
@owielanctot - Any feedback on the additional testimonials? The one you've sent is online.

**Comment by owielanctot** [comment]
Getting another today that should be good

**Comment by BigActual** [comment]
@owielanctot - Will there be any more of these before launch?

**Comment by owielanctot** [comment]
@BigActual Yes- definitely by COB today

**Comment by owielanctot** [comment]
IN the Faurecia testimonial on the About us page it says "forecia" in the signature. Please change to Faurecia

**Comment by BigActual** [comment]
Done. Additional testimonials can be added at any time.
