### ISSUE TITLE
Rework History Content

### ISSUE THREAD

**Issue by owielanctot** [automatedlogistics/Theme2016#64]
The Parker brothers are creating the History page
@BigActual

**Comment by owielanctot** [comment]
[PMF History.docx](https://github.com/automatedlogistics/Theme2016/files/298400/PMF.History.docx)

Here is the first part for the History section. This is all Parker Motor Freight and needs a lot of reworking

**Comment by owielanctot** [comment]
Still waiting on Joe for this. Reminders have been sent. Will keep you posted

**Comment by owielanctot** [comment]
[ALS history- from JP.docx](https://github.com/automatedlogistics/Theme2016/files/307463/ALS.history-.from.JP.docx)

We have the history content from Joe! @BigActual

**Comment by BigActual** [comment]
Reworked 06/13. Left open for comment. Closing with V 1.0
