### ISSUE TITLE
Remove unused social media icons on "Connect" page

### ISSUE THREAD

**Issue by owielanctot** [automatedlogistics/Theme2016#65]

**Comment by owielanctot** [comment]
Remove from footer

**Comment by brashrebel** [comment]
All the social icons should be controlled in settings and only display if a URL is set. @d4mation can we make that happen?

**Comment by d4mation** [comment]
That's actually how it works currently. I've got `#` saved for each link to force them to show up as that way I could showcase how they would look when all were available.

They can be changed through the Customizer and it will affect the Footer and Connect Page globally.

![image](https://cloud.githubusercontent.com/assets/7770631/15689308/5f048106-274c-11e6-910c-7bfcc72c0bd8.png)

**Comment by d4mation** [comment]
Since none were in use, I went ahead and cleared them all out (Including the RSS Button, which is a checkbox in this case).

If any need to be changed/added, you can find it under

```
Customize (In the Admin Bar at the top of the screen) -> Automated Logistics Systems Settings
```

or 

```
Dashboard -> Appearance -> Customize -> Automated Logistics Systems Settings
```
