### ISSUE TITLE
Remove any staff profiles that do not have bio 

### ISSUE THREAD

**Issue by owielanctot** [automatedlogistics/Theme2016#67]
Will be added at a later date

**Comment by BigActual** [comment]
@owielanctot - Can you drop a copy of your profile image here please? Your LI profile shot will do for now, if you have an un-cropped version.

**Comment by owielanctot** [comment]
![olanctot pic](https://cloud.githubusercontent.com/assets/18618395/15717759/730c8d24-27f6-11e6-8667-5d91dea06838.jpg)

**Comment by BigActual** [comment]
@owielanctot , do you have a wider cropped version? Something showing more of the surroundings?

**Comment by owielanctot** [comment]
looking now

**Comment by BigActual** [comment]
Complete.
