### ISSUE TITLE
Move information to sidebar on Connect page

### ISSUE THREAD

**Issue by owielanctot** [automatedlogistics/Theme2016#68]
On the "Connect" page move the credit application info and Joe Parker's info to the rights side under the map

**Comment by BigActual** [comment]
@d4mation - Need a recommendation for the best way to handle this. There will be three items on the right side after this change. Each should be recognizable from the other as we discussed in #34 .

**Comment by d4mation** [comment]
I think handling it the same way as #46 would be best for this. That way there can technically be as many blocks of content in the sidebar as necessary. I'll work on getting that set up.

**Comment by d4mation** [comment]
![image](https://cloud.githubusercontent.com/assets/7770631/15711336/8dd9a328-27db-11e6-98d9-2c7cacbee4be.png)
