### ISSUE TITLE
Arrows on Careers page work backwards

### ISSUE THREAD

**Issue by BigActual** [automatedlogistics/Theme2016#69]
http://alsintersite11.wpengine.com/careers/

The arrows point down when the item is closed and right when open. I believe they should point down when open and right when closed.

**Comment by d4mation** [comment]
I originally had a reason for having them that way, but now I find myself agreeing with you. 

My original idea was that having it start with the arrow facing down while closed was that it made it look similar to dropdown menus and other elements like the Navigation Menu hoping that it would help encourage visitors to click on them. 

![image](https://cloud.githubusercontent.com/assets/7770631/15709712/2c61992c-27d4-11e6-953e-613072717832.png)

However, it looks nicer the other way around. This is a super simple fix. I'll Commit it now.
