### ISSUE TITLE
About Us Page

### ISSUE THREAD

**Issue by d4mation** [automatedlogistics/Theme2016#7]
(Covenant, Etc.)

> Steve: "Is this just covenant, covenant and history, or covenant, history and perfect order?"
> 
> I say the “perfect order” can be referenced here as it pertains to ‘how we think’ but link to it on the next page.

**Comment by d4mation** [comment]
The above information was what I grabbed from the Google Doc. 

The email I received with Page Layout Screenshots shows different information on the About Us page. It's set up so any content can happily live in there (via the built-in Content Editor), so I based it off the Screenshot.

![image](https://cloud.githubusercontent.com/assets/7770631/14151641/dca6da24-f67c-11e5-8951-6b5d6ae10771.png)

I don't know where the links in the content are meant to go, so for now they go nowhere (`#`).

I will need to add a field to the page for the "Contact us today" text and link I believe as the UX for that currently is pretty bad.

**Comment by BigActual** [comment]
Smart employees goes to the staff archive page. US, Canada & Mexico page doesn't exist yet, and may not. Pull the hyperlink for now.

**Comment by d4mation** [comment]
Updated the hyperlinks.
