### ISSUE TITLE
Are Staff in the proper sections?

### ISSUE THREAD

**Issue by BigActual** [automatedlogistics/Theme2016#70]
@owielanctot - Are all staff in the correct sections? Executive Team, Lead Representatives & Staff

Without walking down the path of "Departments", are the current sections appropriately titled? I think so, but have a suspicion that they could be tweaked. Would appreciate your input.

**Comment by owielanctot** [comment]
Hey @bigactual the more I look at it the more I would like to do departments. Just three: 
Executive team: Joe, Paul, Jacob
Operations: Fred, Matt, Andy, Nick, Chris, Colin, Julie
Sales: Bob, Faye, Luis, Owie, Jason, Jeremy, Mary Margaret, Laurie

**Comment by BigActual** [comment]
@d4mation - Would you please change these section headings?

**Comment by d4mation** [comment]
Section Headings have been changed. The Staff will just need to be reassigned to their new Departments.

**Comment by BigActual** [comment]
I'll reassign existing staff now.

**Comment by BigActual** [comment]
Reassigned. @d4mation is giving us the tools for reorganize the list.
@owielanctot, please reverify that everyone is sectioned out correctly. I question some of my choices for people like Bob.

**Comment by d4mation** [comment]
Staff are now automatically reorganized based on their Position/Title. 

Now they will use the following order:
1. Presidents
2. Vice-Presidents
3. Directors
4. Leads

If there are multiple within a Department (Say, multiple Directors), they will be ordered by Last Name.

**Comment by owielanctot** [comment]
Just looked. Some people are in the wrong spot. Please organize as follows:

Executive team: Joe, Paul, Jacob
Operations: Fred, Matt, Andy, Nick, Chris, Colin, Julie
Sales: Bob, Faye, Luis, Olivia, Jason, Jeremy, Mary Margaret, Laurie

**Comment by d4mation** [comment]
I've gone through and reassigned all the Staff accordingly. However, they are not in that exact order due to the sorting rules I outlined above.

Are you wanting them in that exact ordering, or was that just how you came across them while writing out who goes in which department?

**Comment by owielanctot** [comment]
Looks great! It was in no particular order. In the sales section if we could get the intern listed last that would be great, otherwise I like it! Thank you

**Comment by d4mation** [comment]
Excellent! I'll look into adjusting the sorting to place Interns at the bottom.

**Comment by d4mation** [comment]
I've got it set now to place any Interns at the end of a Department list! Changes are up on the site now.
