### ISSUE TITLE
Restyle Customer Page for Milestone 1.1.

### ISSUE THREAD

**Issue by BigActual** [automatedlogistics/Theme2016#71]
@owielanctot - As new products are introduced, I want to ensure that they fit nicely into a visually stunning and logical/useful layout. The workflow for end users has to seem natural and we don't want a page of ongoing intermingled services. 

With that in mind, we need to clearly understand how the "products" are grouped so we can create a simple way to both manage and interact with them. Roughly 20 products are on their way to us. What are your thoughts on how to separate them into useful groups? Ones that both customer and admin will understand?

**Comment by owielanctot** [comment]
Products:
Brokerage
Contract Trans
Consol/Deconsol
Engineering
Warehousing

Service:
Van
Reefer
Flatbed
Specialized
Expedites
Ground Expedite
Air Expedite
LTL
Laredo Warehouse
Mexico
Transload – Laredo
Enterprise Management
CIR Account Management
Spot Market
3PL
Plant Move & Project Mgmt

**Comment by owielanctot** [comment]
I will work on a further breakdown

**Comment by owielanctot** [comment]
See document on #58

**Comment by d4mation** [comment]
Copying here for my own convenience: 

PRODUCTS
- Brokerage
- Contract Trans
- Consol/Deconsol
- Engineering
- Warehousing

SERVICES
- Modes of transport
  - Van
  - Reefer
  - Flatbed
  - Specialized
  - Ground Expedite
  - Air Expedite
  - LTL
  - Spot Market
- International Services
  - Laredo Warehouse
  - Mexico
  - Transload – Laredo
- Continuous Improvement
  - Enterprise Management
  - CIR Account Management
- Special Projects
  - 3PL
  - Plant Move & Project Management

**Comment by d4mation** [comment]
Progress can be seen on the Develop Branch within this Repository as well as [here](http://alsintersite11.staging.wpengine.com/customers/) on the Staging Site.

The Archive Grid is still very much a work-in-progress. The Products Single is looking pretty good, however.

So far only [LTL](http://alsintersite11.staging.wpengine.com/product-service/less-than-truckload-ltl/) is built out as I had the data for that. All the other items don't have any information associated with them and are there for visual purposes currently. I know the plan is to add these are the data is gathered for the Live Site.

**Comment by owielanctot** [comment]
@d4mation Love the mock-up! So good to see it take shape. Am I correct that @brashrebel will work on these icons/images when he returns? 

On the LTL page we will be adding a customer/3rd party story, and a video. Considering this, do we need to restyle what you have done to the page? This format of product info, testimonial, video, will hold true to all products, but content will come in on a rolling schedule. Let me know what you think.

Thank you!

**Comment by d4mation** [comment]
I have set the Product/Services Pages up so that each of those text sections is its own Editor and just about anything can be placed in there&mdash;including Videos. As many sections as necessary can be added in there, so there's just about no limits!

![image](https://cloud.githubusercontent.com/assets/7770631/16660389/0f691078-443c-11e6-83f5-464cbe4162c8.png)

I'm not sure about the icons/images. Scheduling for that would be up to @brashrebel.

**Comment by BigActual** [comment]
Could you please adjust the way these display so that each row is vertically aligned at the top. Products with a two line description start higher. Let's stop that from occurring.

**Comment by d4mation** [comment]
They are all vertically aligned at the top now 👍
