### ISSUE TITLE
Terms and Conditions

### ISSUE THREAD

**Issue by owielanctot** [automatedlogistics/Theme2016#73]
We need a tab referencing the terms and conditions on the homepage.  @BigActual  you mentioned putting it in the footer under the "Connect" column. If you still like that, it works for me

**Comment by BigActual** [comment]
@d4mation , please add a link to the footer, as Owie describes above, in the Connect column.  Thanks.

**Comment by d4mation** [comment]
Added to the "Connect" area in the footer.
