### ISSUE TITLE
Editing the About Us page

### ISSUE THREAD

**Issue by owielanctot** [automatedlogistics/Theme2016#74]
What is we took the "Let's get the conversation Rolling" and the contact us today button below it, made it bigger, and put it above the Faurecia on the right?

Or will moving the button deter action from a visitor?

Further edits to content coming shortly

**Comment by owielanctot** [comment]
[About Us Edit.docx](https://github.com/automatedlogistics/Theme2016/files/305118/About.Us.Edit.docx)

**Comment by BigActual** [comment]
Okay, I hated the bouncing around of the copy so I gave it a pretty substantial reorganization. Please provide feedback one more time @owielanctot

**Comment by BigActual** [comment]
@d4mation, Can we slide a sidebar in here before launch or is this a major overhaul that should wait for 1.1?

**Comment by d4mation** [comment]
A sidebar should be a quick addition before launch. I'm thinking handling it like the Sidebar on the Customers and Carriers pages will work best for this 👍

**Comment by d4mation** [comment]
@BigActual @owielanctot Sidebar has been implemented!

**Comment by owielanctot** [comment]
@BigActual the copy looks good! Having Paul edit to confirm it is accurate info. 

Are all of the blue headers the same size? I can't tell.

@d4mation sidebar looks good too!

**Comment by BigActual** [comment]
@d4mation - Minor layout tweak to the sidebar. Could we have a touch more padding between items please?

**Comment by d4mation** [comment]
@BigActual, yeah I'll go ahead and add some for this page. I think it looks so squished in this case since the image for the Testimonial below it has a white background.

(The Orange shows the Margin between the elements)
![image](https://cloud.githubusercontent.com/assets/7770631/15908427/aa1bd90c-2d8f-11e6-8b46-8208889563b9.png)

**Comment by d4mation** [comment]
Bumped it up to 2em for the bottom margin on that element. How does it look on your end, @BigActual?

**Comment by owielanctot** [comment]
In the sentence "We are truly Beyond Driven, providing the best supply chain services in the industry." Insert “3PL” in front of “supply chain”  

Second paragraph under We understand our role

**Comment by owielanctot** [comment]
Add as another bullet under end to end supply chain management:

Strong relationships with motor carriers of every specialty

**Comment by BigActual** [comment]
Done
