### ISSUE TITLE
Edits to ALS Team page

### ISSUE THREAD

**Issue by owielanctot** [automatedlogistics/Theme2016#76]
Move Bob Ostrander from Sales category up to Executive team

Edited picture of Colin McCloskey attached. McCloskey Title: Senior Account Manager

Title for Fred Botello, Jacob Kosiara, Paul McDonald, Ostrander: change the comma to "of" 
Matt Eckler title- Senior Director of Business Development
Jeremy Filar title: Inside Sales Executive 
Luis Rivas title: International Account Executive

I will be editing profiles to make sure they are all in the same tone

![colin-mccloskey web photo](https://cloud.githubusercontent.com/assets/18618395/15908739/31e6a47e-2d91-11e6-9757-14c11c8d79b5.jpg)

**Comment by BigActual** [comment]
Done
