### ISSUE TITLE
Customers Page Content Tweaks

### ISSUE THREAD

**Issue by owielanctot** [automatedlogistics/Theme2016#78]
Make the statement "Customers can depend on ALS to:" bigger or in blue like a header

**Comment by d4mation** [comment]
All set!

**Comment by BigActual** [comment]
Whoa hold on there tigers... That's a global design change we're talking about. Both on and off line. How about if we step back to increasing the size a bit instead of going blue.

**Comment by d4mation** [comment]
Reverted to **bold** for the time being.

Within the WYSIWYG editor there isn't really a way to increase Font Size without using a Header (Which per the Style Guide are all Blue). 

Outside of implementing a Shortcode to control Font Size I'm not sure what the best way would be to give control over that within the WYSIWYG editor... Switching to the `Text` tab to input straight HTML is possible, but that's not very user-friendly.

**Comment by BigActual** [comment]
I was wrong. I misunderstood the request to be one to change the h2 styling globally, instead of what it was, to change the style of this type from paragraph to h2. My mistake, please accept my apology Eric.

**Comment by d4mation** [comment]
It's no problem! I was trying to ensure that I was understanding what you were saying as well. A global design change would certainly be undesirable.

Shall I go ahead and change this back to using a Heading rather than bold text?

**Comment by BigActual** [comment]
Nope I've done it. Thanks for understanding.
