### ISSUE TITLE
Search and Search Results

### ISSUE THREAD

**Issue by d4mation** [automatedlogistics/Theme2016#8]
> As content grows, this will become more useful to end users. 
> For sure, this should include a list of relevant pages, posts and CPTs. For example, what would a useful search results page look like for an End User search on ‘Mexico’ or ‘Shipping North America’?
> 
> Pages listed before posts.
> 
> Excerpts only with links to “Read More”
> 
> Featured images as small-hero thumbnails (??)

**Comment by d4mation** [comment]
@BigActual @skarritt 

In the mockups of the design, there isn't a Search Bar/Button anywhere that I can see.

Is there a preference to how this should be implemented? I'm trying to think of ways to ensure that it works well on Desktop and Mobile without any weird hiccups.

**Comment by BigActual** [comment]
Somewhere easy to access. Pop it in where you think it's effective and we can iterate if necessary.

**Comment by d4mation** [comment]
There's now a nice Search Button that pops up an Overlay on both Desktop and Mobile. 

On Mobile, it closes the Off-Canvas Menu automatically to bring it to the Overlay. Due to the size of the Logo, I couldn't fit the Search Icon in the header very well on Mobile.

This avoids putting an unsightly Text Box in a static location like the Header.

The small animation is done via SVG, so there should be no cross-browser issues.

![image](https://cloud.githubusercontent.com/assets/7770631/14286483/33ad112c-fb1d-11e5-9a51-a977c01abea9.png)

I still need to get it to search for Pages properly, but that should be a simple Filter in WP.

Right now it can be tested by typing "Hello" which will result in the "Hello, World!" default Post.

**Comment by joelworsham** [comment]
It would be radical if when the overlay came up, the text field automatically gained focus

**Comment by d4mation** [comment]
Good point! I'll set that up in just a moment.

**Comment by joelworsham** [comment]
This overlay is fantastic though

**Comment by BigActual** [comment]
Awesome.

**Comment by d4mation** [comment]
Threw in a `usort` to force `Pages` to show before anything else.

Also made the Text Field gain focus as soon as the Overlay is active. Added in the ability to hit `esc` to close it out.

Should be good to go with that, at least for now. As @BigActual said, it can always be iterated upon.
