### ISSUE TITLE
Modify padding on the left and right of the mobile experience

### ISSUE THREAD

**Issue by BigActual** [automatedlogistics/Theme2016#80]
![image](https://cloud.githubusercontent.com/assets/8271108/15938943/8f187bec-2e43-11e6-9e2b-fd966bc2a172.png)
Make the white space left of the red line and right of the image and copy equal to the white space between the red line and the image. This will make the images slightly smaller.  I don't want to shrink text size to accomplish this. I'd prefer that the width of the copy shrink instead

**Comment by d4mation** [comment]
Looks pretty even for me now.

![image](https://cloud.githubusercontent.com/assets/7770631/15940645/f2afcdc0-2e4a-11e6-8b23-256d05123b78.png)
