### ISSUE TITLE
Tweak on Carriers page

### ISSUE THREAD

**Issue by owielanctot** [automatedlogistics/Theme2016#82]
Could you please make "Carriers can count on ALS to" look like the other blue headers

**Comment by BigActual** [comment]
Owie, this is a global change. Let's look at going with just a larger font size first.

**Comment by owielanctot** [comment]
Sounds good.

**Comment by BigActual** [comment]
OK, I made a mistake on #78 that I carried here @owielanctot. I apologize. This has been taken care of. However, I don't like this change. I believe everything from that statement down was really written to support the H2 above it. Not to be a separate H2. Here's an article I wrote on the topic a few months ago: http://realbigmarketing.com/2015/12/how-to-use-header-tags-in-a-blog-post-h1-through-h6/

**Comment by BigActual** [comment]
Completed 06/13, but left open for comment. Closing in conjunction with V 1.0.
