### ISSUE TITLE
Contact change on Connect page

### ISSUE THREAD

**Issue by owielanctot** [automatedlogistics/Theme2016#83]
We're going to remove Joe from the contact us page and replace with Paul. 

Box on bottom right corner:

Paul McDonald, Vice President of Business Development
Phone: same
Mobile: remove
Fax: 517-782-0125
pmcdonald@automatedlogistics.com

**Comment by owielanctot** [comment]
On the credit application remove Jo'es email and add accounting@automatedlogistics.com
Fax: same

**Comment by owielanctot** [comment]
Do change the fax under Paul's name. Keep the same fax number that is there -888-764-6225

**Comment by BigActual** [comment]
@d4mation I'm trying to wrap a few things before leaving. Would you mind addressing this please?

**Comment by d4mation** [comment]
This should be good to go. Just confirming that I've got things as they should be before I close this:

## Credit Application

Credit Application

If you’re interested in filling out our credit application, please use this form and send it to us by email, fax or mail.
Email: accounting@automatedlogistics.com
Fax: 1-888-764-6225
Mail: Automated Logistics Systems, 3517 Scheele Drive, Jackson, MI 49202

## Paul McDonald's Section

Paul McDonald, Vice President of Business Development
Phone: 1-800-551-9399
Fax: 1-517-782-0125
pmcdonald@automatedlogistics.com

**Comment by owielanctot** [comment]
Use the other fax for Paul's contact. 1-888-764-6225

I didn't mean to add the other one before.

Other than that, looks good to go!

**Comment by d4mation** [comment]
All set!
