### ISSUE TITLE
Grammar edits on Staff page

### ISSUE THREAD

**Issue by owielanctot** [automatedlogistics/Theme2016#84]
- [x] Joe Parker: Remove comma after "Has favorite part of running ALS"
- [x] Paul" In first line of second paragraph change understand to understands
- [x] Colin: fiancée spelled two different ways. Spell both like fiancée
- [x] Luis: Change south to Southern. This is before U.S. States.
- [x] Faye: In first sentence remove "has." In the second paragraph remove the "and" between enthusiast and has raced ... replace with a comma. 

Colin's picture on my phone is the brighter edited version, but not on my desktop.
- [x] On some of the profiles it says "read more" and on others it doesn't if the first paragraph was shorter. But this makes it look like half of their bios got cut off, or there isn't anymore info. Can we have "read more" on all of them?

**Comment by d4mation** [comment]
I'll look into seeing what I can do to make "Read More" show for each of them on that page.

For Colin's Picture, my guess is that this is a caching issue on your phone. My laptop was showing the darker one just now until I cleared out my cache.

On an Android device, 
1. Open Chrome and hit the three dots in the upper right hand corner
2. Open History and hit "Clear Browsing Data" and ensure "Cached Images and Files" is selected.

On an iPhone,
1. Press Settings -> Safari.
2. Scroll down and tap Clear History and Website Data.
3. Tap Clear History and Data.

**Comment by d4mation** [comment]
It now shows "Read More..." for every entry on the Staff page, regardless of length.

Let me know if you're able to see the correct image for Colin after clearing out your caches when you get the chance!

**Comment by owielanctot** [comment]
I see the Read mores and the picture is the right one! Thanks for the help on that

**Comment by d4mation** [comment]
No problem!
