### ISSUE TITLE
Edits to About Us Page

### ISSUE THREAD

**Issue by owielanctot** [automatedlogistics/Theme2016#85]
Under "End to End Supply chain management" delete everything and put:

In 1992 our customers pushed us to become a 3PL. Since then we’ve pushed our clients forward offering wider, more flexible and customized, end-to-end supply chain management solutions. We’ve enhanced our ability to offer low-risk, high-value solutions including:

• Services that support all nodes and flows in a customer’s supply chain. Nodes and flows start with the customer order and end with the delivery
o   Origin or supplier
o   Origin warehouse
o   Origin consolidation center or crossdock
o   All Origin Transportation Modes including TL and LTL services with vans, reefers, flatbeds and specialized equipment
o   Brokerage or transborder services
o   Border consolidation service
o   All destination transportation modes including TL and LTL services with vans, reefers, flatbeds and specialized equipment
o   Destination warehouse or consolidation
o   Final delivery to customer
• A la carte segmentation of transportation management
• Transportation Engineering and Transportation Management Services

**Comment by owielanctot** [comment]
Also, Under "We Unserstand our role:

Add as the last bullet after "Support our customer requirements...":
Strong relationships with motor carriers of every specialty

**Comment by d4mation** [comment]
All set!
