### ISSUE TITLE
Covenant Video

### ISSUE THREAD

**Issue by owielanctot** [automatedlogistics/Theme2016#87]
On the screen that has the covenant video- the "Find out how" button on the home page takes you here.

We need to add the text of the covenant in case someone doesn't have their sound on. You can place it on there stylistically however you think is best.

Our Covenant
ALS succeeds because we're committed to building strong customer relationships right from the start. Our passion is demonstrated by a job well done. We provide exemplary service delivered by employees who genuinely care. 

Every move we make matters- how we work, how we think, how we communicate. We're sincerely "Beyond Driven."

**Comment by owielanctot** [comment]
Also- on this screen can we make a yellow call to action bar that is something like "Connect" and it takes you right to the connect page.

**Comment by d4mation** [comment]
I've added this to the Covenant Video Overlay but for Desktop only. This area has a limited amount of space that we are able to utilize so for Mobile it would not have been able to fit.

This section scrolls with you as you scroll down the page, so it is limited by the vertical height of the screen of whatever device you're viewing the website on.

Here's what this section looked like before on Mobile:
![image](https://cloud.githubusercontent.com/assets/7770631/16016838/f0ffbb52-316a-11e6-9cb1-f049e4ade398.png)

Here it is now on Desktop:
![image](https://cloud.githubusercontent.com/assets/7770631/16016885/2a526f76-316b-11e6-91e7-b2121ebf643f.png)

Ideas for Mobile implementation of this feature will be over at #88.

**Comment by owielanctot** [comment]
I like the desktop look! I'm open to suggestions as far as mobile/desktop parity
