### ISSUE TITLE
Services Archive Page

### ISSUE THREAD

**Issue by d4mation** [automatedlogistics/Theme2016#9]
> Steve: "Does this page require call to action or supporting content beyond presentation of an archive list of services? What does this page look like and what function does it serve?"
> 
> Kyle: "I'm envisioning V1 of this just being a static page. We don't have a plan for breaking apart services I think. Though it isn't a super big deal so I don't mind incorporating it. But I didn't plan on a services CPT. Just a page."

**Comment by d4mation** [comment]
I opted to make it just a Page for now. It utilizes a Repeater in the Page Template to output the information. 

I thought about it some, and a CPT with an Archive for this would be a bit strange, since there are likely a set number of Services and therefore having enough to ever need pagination or other Archive features wouldn't be likely. The Services themselves can be given Child Pages of the Services Page and be linked to via the Buttons if necessary. I think that implementation may be best.

What do you think, @brashrebel?

Local screenshot:
![image](https://cloud.githubusercontent.com/assets/7770631/14154174/1bf1e0c8-f689-11e5-936a-80729e7e04eb.png)

**Comment by brashrebel** [comment]
Fine for now.

**Comment by d4mation** [comment]
I'll go ahead and close this Issue then. If we go the CPT route, I'll track it in another Issue.

**Comment by d4mation** [comment]
Actually, looking at #2 again, there may be a need for a CPT. 

Maybe not to output on this page, but at least to hold more specific data on individual Services.

I'll re-open this until we can narrow things down.

**Comment by BigActual** [comment]
I'm on the fence on this. I'm more concerned about styling on individual services than I am about hthe number of services that will be available. I don't want the client or I to think about "how" to make the content look right each time a new service is added. There will end up being about 10 services I'm guessing. These will be developed over time.

**Comment by d4mation** [comment]
I opted to convert it to a CPT Archive-Loop within the Page Template. It looks the same as it does in the screenshot above, but the data is now sourced via the `Services` CPT. This will help keep things centralized and hopefully make things more clear to the User.

Right now it outputs any and all Services in `post_date` order. The order can be changed however it needs to be and pagination can be added if needed. However, pagination could be weird without a separate, proper, CPT Archive page for it to be redirected to as the rest of the Page would stay the same and may be confusing to Visitors to the site.
