### ISSUE TITLE
Add video to hero image on home page

### ISSUE THREAD

**Issue by BigActual** [automatedlogistics/Theme2016#90]
@d4mation would you please place this video immediately to the left of the call to action, within the hero image, on the home page.

I thought i could do it myself, but i can not. 

https://youtu.be/jx2gYwnYljw

Thanks

**Comment by d4mation** [comment]
I've gone ahead and added a field for this to the Homepage. A Video can now be easily added to the left-hand side next to the Call To Action 👍 

![image](https://cloud.githubusercontent.com/assets/7770631/16730992/d6fd1e72-4743-11e6-9b7f-e49a9d597652.png)
