### ISSUE TITLE
Add news page

### ISSUE THREAD

**Issue by brashrebel** [automatedlogistics/Theme2016#95]
- [x] Link in main menu under About Us
- [x] Link in footer under About Us section
- [x] New section on home page. This will be a fourth item on the red line below Connect with us.

@owielanctot can you please comment here with the title, text, button text and image that you would like used in this new section on the home page? Thanks!

**Comment by owielanctot** [comment]
Title: News
Text: We want to keep our customers informed. Find out more Automated Logistics Systems, industry trends and issues, and supply chain information
Button text: Read On
Image: We don't have any original photos that work here. Do you have anything on your end? Or some transportation images in general? Maybe a close up of some big, impressive tires? I'm ok with anything!

**Comment by brashrebel** [comment]
I don't have any images. We can buy some stock photo (or you can) or we can pull something from one of the photo shoots. I don't have access to those (that I know of). Also the image should ideally relate to "News about ALS" so I envision something that includes ALS people or at least some branded imagery.

**Comment by owielanctot** [comment]
@brashrebel Laurie and I are on the hunt for a suitable photo. Can we get the rest of the provided info up on the News page? Do we need anything for the landing page where all the articles will be housed?

**Comment by brashrebel** [comment]
We don't need anything for the News page. We'll take care of that. This requested information isn't for the _News_ page. It is for the _Home_ page in the section that links to the News page. So putting it up on the home page with something missing like the image might look worse than having nothing there. Make sense?

**Comment by d4mation** [comment]
Over in #44 we talked about having the image that loads being related to the most Recent Article rather than being static.

However, having a static image would be helpful for instances where an image isn't attached to a News Post.

Or are these two sections meant to be different?

**Comment by owielanctot** [comment]
Yes, totally makes sense. Can we get the set up for the Home page on the staging site? We can use any photo as a place holder. I hope to have the actual photo later today. We have two blog posts up and ready and I'd like to go live with it soon.  Thank you!

@d4mation I like the idea of a rotating photo, but will that look ok if they aren't Photoshopped/ the same quality as the other images on the site. I'm sure a lot of the pictures connected to articles won't be as nice due to time/resources.

**Comment by d4mation** [comment]
That's what I was thinking too. Getting consistent sizing and quality for something rotating like that would be very difficult.

I just thought I'd bring it up in case these two Issues were related.

**Comment by brashrebel** [comment]
I'd lean against rotating the image. The text and title will remain the same and the image will be out of context. We need a static image that conveys "News about ALS".

And I'm still waiting on Paul for approval. I'll follow up with him soon.

**Comment by owielanctot** [comment]
[Web Pics 2.zip](https://github.com/automatedlogistics/Theme2016/files/370015/Web.Pics.2.zip)

Here ii the picture we would like to use for the News link on the home page
