### ISSUE TITLE
Linking to Product Pages

### ISSUE THREAD

**Issue by owielanctot** [automatedlogistics/Theme2016#96]
@brashrebel While we are waiting on the phase 2 design for the Customers page, can we use the current layout to link to product information? Specifically, we have the LTL page pretty much ready to go, besides adding the video and testimonial. Could we hyperlink the words 'Less than Truckload LTL" on the current customers page?

**Comment by owielanctot** [comment]
Any word on this?

**Comment by brashrebel** [comment]
Since we don't have the _template_ ready yet for the products I don't think we can make this change _quite_ yet. However, we're working on this very soon so it shouldn't remain an issue long.

**Comment by owielanctot** [comment]
Sounds good. What's the potential timeline for the template? Possibly this week?

**Comment by brashrebel** [comment]
Definitely this week. It is actually in progress.

**Comment by owielanctot** [comment]
Awesome! Thank you
